apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd:2.4
          ports:
            - containerPort: 80

          # Env vars from Secret (creates $hello)
          envFrom:
            - secretRef:
                name: app-secret

          volumeMounts:
            # ConfigMap -> /opt/hello.txt
            - name: hello-config-vol
              mountPath: /opt/hello.txt
              subPath: hello.txt
              readOnly: true
            # Secret -> /opt/secret.txt
            - name: app-secret-vol
              mountPath: /opt/secret.txt
              subPath: hello
              readOnly: true

      volumes:
        - name: hello-config-vol
          configMap:
            name: hello-config
        - name: app-secret-vol
          secret:
            secretName: app-secret