apiVersion: v1
kind: Namespace
metadata:
  name: apache-dev
---
apiVersion: v1
data:
  index.html: |
    <html>
      <head><title>Apache - DEV</title></head>
      <body style="font-family: sans-serif;">
        <h1>Apache - DEV</h1>
        <p>This is the <b>DEV</b> environment.</p>
      </body>
    </html>
kind: ConfigMap
metadata:
  name: apache-index
  namespace: apache-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache
  namespace: apache-dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
        env: dev
    spec:
      containers:
        - image: httpd:2.4.59
          name: httpd
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs/index.html
              name: html
              subPath: index.html
      volumes:
        - configMap:
            name: apache-index
          name: html
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache
  name: apache
  namespace: apache-dev
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: apache
  type: ClusterIP
